### ISSUE TITLE
Insert any heading results in a crash.

### ISSUE THREAD

**Issue by alfredbuehler** [creecros/MarkdownPlus#12]
- PHP8 only, still works on PHP7.
- The prior version 1.1.1 still works.

Enter something like 
```
# Foo

Lorem ipsum dolor sit amet…
```
in a task description and the app crashes as soon you want to display that task. Remove the '#', no crash. Just the same with '-' or '=' for headings.

```
Fatal error: Uncaught TypeError: 
Cannot access offset of type string on string in 
/var/www/...kanboard-1.2.26/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php:209 
Stack trace: 
#0 /var/www/...kanboard-1.2.26/plugins/MarkdownPlus/vendor/erusev/parsedown/Parsedown.php(232): ParsedownExtra->blockHeader(Array, Array) 
#1 /var/www/...kanboard-1.2.26/plugins/MarkdownPlus/vendor/erusev/parsedown/Parsedown.php(39): Parsedown->lines(Array) 
#2 /var/www/...kanboard-1.2.26/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php(46): Parsedown->text('Organize this p...') 
#3 /var/www/...kanboard-1.2.26/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php(63): ParsedownExtra->text('Organize this p...') 
#4 /var/www/...kanboard-1.2.26/app/Template/task/description.php(5): Kanboard\Plugin\MarkdownPlus\Helper\MarkdownPlusHelper->markdown('Organize this p...', false) 
#5 /var/www/...kanboard-1.2.26/app/Core/Template.php(83): include('/var/www/...') 
#6 /var/www/...kanboard-1.2.26/app/Template/task/show.php(11): Kanboard\Core\Template->render('task/descriptio...', Array) 
#7 /var/www/...kanboard-1.2.26/app/Core/Template.php(83): include('/var/www/...') 
#8 /var/www/...kanboard-1.2.26/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render('task/show', Array) 
#9 /var/www/...kanboard-1.2.26/app/Helper/LayoutHelper.php(74): Kanboard\Helper\LayoutHelper->subLayout('task/layout', 'task/sidebar', 'task/show', Array) 
#10 /var/www/...kanboard-1.2.26/app/Controller/TaskViewController.php(67): Kanboard\Helper\LayoutHelper->task('task/show', Array) 
#11 /var/www/...kanboard-1.2.26/app/Core/Controller/Runner.php(77): Kanboard\Controller\TaskViewController->show() 
#12 /var/www/...kanboard-1.2.26/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() 
#13 /var/www/...kanboard-1.2.26/index.php(9): Kanboard\Core\Controller\Runner->execute() 
#14 {main} thrown in /var/www/...kanboard-1.2.26/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 209 
```
I reverted to MarkdownPlus 1.1.1 until this might be fixed.

**Comment by Chaosmeister** [comment]
looks like parsedown and parsedown-extra got out of sync somehow

their own versioning doesn't cover this case.

**Comment by creecros** [comment]
ut o, what did I do?!

I'll take a look at the prs tonight @Chaosmeister
